version: "3"
services:
  selenium-hub:
    image: selenium/hub:latest
    ports:
      - "4444:4444"

  edge:
    image: shabfactor/node-edge-browser:latest
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - VNC_NO_PASSWORD=1
      - SCREEN_WIDTH=${SCREEN_WIDTH}
      - SCREEN_HEIGHT=${SCREEN_HEIGHT}
    ports:
      - "5555:5555"
      - "5900:5900"

  firefox:
    image: selenium/node-firefox-debug:latest
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - VNC_NO_PASSWORD=1
      - SCREEN_WIDTH=${SCREEN_WIDTH}
      - SCREEN_HEIGHT=${SCREEN_HEIGHT}
    ports:
      - "5556:5555"
      - "5901:5900"

  chrome:
    image: selenium/node-chrome-debug:latest
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - VNC_NO_PASSWORD=1
      - SCREEN_WIDTH=${SCREEN_WIDTH}
      - SCREEN_HEIGHT=${SCREEN_HEIGHT}
    ports:
      - "5557:5555"
      - "5902:5900"   