/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

import * as msRest from "@azure/ms-rest-js";


export const UserDetails: msRest.CompositeMapper = {
  serializedName: "UserDetails",
  type: {
    name: "Composite",
    className: "UserDetails",
    modelProperties: {
      email: {
        required: true,
        serializedName: "email",
        type: {
          name: "String"
        }
      },
      firstName: {
        required: true,
        serializedName: "firstName",
        type: {
          name: "String"
        }
      },
      lastName: {
        required: true,
        serializedName: "lastName",
        type: {
          name: "String"
        }
      },
      password: {
        required: true,
        serializedName: "password",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const Email: msRest.CompositeMapper = {
  serializedName: "Email",
  type: {
    name: "Composite",
    className: "Email",
    modelProperties: {
      email: {
        required: true,
        serializedName: "email",
        type: {
          name: "String"
        }
      },
      password: {
        serializedName: "password",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const ErrorModel: msRest.CompositeMapper = {
  serializedName: "ErrorModel",
  type: {
    name: "Composite",
    className: "ErrorModel",
    modelProperties: {
      code: {
        required: true,
        nullable: false,
        serializedName: "code",
        type: {
          name: "Number"
        }
      },
      description: {
        required: true,
        serializedName: "description",
        type: {
          name: "String"
        }
      },
      method: {
        required: true,
        serializedName: "method",
        type: {
          name: "String"
        }
      },
      path: {
        required: true,
        serializedName: "path",
        type: {
          name: "String"
        }
      },
      service: {
        required: true,
        serializedName: "service",
        type: {
          name: "String"
        }
      },
      status: {
        required: true,
        nullable: false,
        serializedName: "status",
        type: {
          name: "Number"
        }
      },
      timestamp: {
        required: true,
        serializedName: "timestamp",
        type: {
          name: "DateTime"
        }
      }
    }
  }
};

export const ErrorResponse: msRest.CompositeMapper = {
  serializedName: "ErrorResponse",
  type: {
    name: "Composite",
    className: "ErrorResponse",
    modelProperties: {
      error: {
        serializedName: "error",
        type: {
          name: "Composite",
          className: "ErrorModel"
        }
      }
    }
  }
};

export const PasswordDetails: msRest.CompositeMapper = {
  serializedName: "PasswordDetails",
  type: {
    name: "Composite",
    className: "PasswordDetails",
    modelProperties: {
      code: {
        required: true,
        serializedName: "code",
        type: {
          name: "String"
        }
      },
      email: {
        required: true,
        serializedName: "email",
        type: {
          name: "String"
        }
      },
      password: {
        required: true,
        serializedName: "password",
        type: {
          name: "String"
        }
      },
      type: {
        required: true,
        serializedName: "type",
        type: {
          name: "Object"
        }
      }
    }
  }
};

export const ServiceResponse: msRest.CompositeMapper = {
  serializedName: "ServiceResponse",
  type: {
    name: "Composite",
    className: "ServiceResponse",
    modelProperties: {
      email: {
        required: true,
        serializedName: "email",
        type: {
          name: "String"
        }
      },
      maxAttempts: {
        serializedName: "maxAttempts",
        type: {
          name: "Number"
        }
      },
      remainingAttempts: {
        serializedName: "remainingAttempts",
        type: {
          name: "Number"
        }
      }
    }
  }
};

export const ValidationDetails: msRest.CompositeMapper = {
  serializedName: "ValidationDetails",
  type: {
    name: "Composite",
    className: "ValidationDetails",
    modelProperties: {
      code: {
        required: true,
        serializedName: "code",
        type: {
          name: "String"
        }
      },
      email: {
        required: true,
        serializedName: "email",
        type: {
          name: "String"
        }
      },
      type: {
        required: true,
        serializedName: "type",
        type: {
          name: "Object"
        }
      }
    }
  }
};

export const RegistrationDetails: msRest.CompositeMapper = {
  serializedName: "RegistrationDetails",
  type: {
    name: "Composite",
    className: "RegistrationDetails",
    modelProperties: {
      email: {
        required: true,
        serializedName: "email",
        type: {
          name: "String"
        }
      },
      firstName: {
        required: true,
        serializedName: "firstName",
        type: {
          name: "String"
        }
      },
      lastName: {
        required: true,
        serializedName: "lastName",
        type: {
          name: "String"
        }
      }
    }
  }
};
